//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Civica.InfoPath {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Defaults {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Defaults() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Civica.InfoPath.Defaults", typeof(Defaults).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] manifest {
            get {
                object obj = ResourceManager.GetObject("manifest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;xsd:schema targetNamespace=&quot;http://schemas.microsoft.com/office/infopath/2003/myXSD/2017-07-27T23:30:35&quot; xmlns:my=&quot;http://schemas.microsoft.com/office/infopath/2003/myXSD/2017-07-27T23:30:35&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;xsd:element name=&quot;myFields&quot;&gt;
        ///		&lt;xsd:complexType&gt;
        ///			&lt;xsd:sequence&gt;
        ///				&lt;xsd:element ref=&quot;my:testInput&quot; minOccurs=&quot;0&quot;/&gt;
        ///			&lt;/xsd:sequence&gt;
        ///			&lt;xsd:anyAttribute processContents=&quot;lax&quot; namespace=&quot;http://www.w3.org [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myschema {
            get {
                return ResourceManager.GetString("myschema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;my:myFields xmlns:my=&quot;http://schemas.microsoft.com/office/infopath/2003/myXSD/2017-07-27T23:30:35&quot; xmlns:xd=&quot;http://schemas.microsoft.com/office/infopath/2003&quot;&gt;
        ///	&lt;my:testInput/&gt;
        ///	&lt;xd:SchemaInfo LocalName=&quot;myFields&quot; NamespaceURI=&quot;http://schemas.microsoft.com/office/infopath/2003/myXSD/2017-07-27T23:30:35&quot;&gt;
        ///		&lt;xd:Namespaces&gt;
        ///			&lt;xd:Namespace LocalName=&quot;myFields&quot; NamespaceURI=&quot;http://schemas.microsoft.com/office/infopath/2003/myXSD/2017-07-27T23:30:35&quot;/&gt;
        ///		&lt;/xd:Namespaces&gt;
        ///	&lt;/xd:SchemaInfo&gt;
        ///&lt;/my:myFiel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sampledata {
            get {
                return ResourceManager.GetString("sampledata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;?mso-infoPathSolution name=&quot;urn:schemas-microsoft-com:office:infopath:Form1:-myXSD-2017-07-27T23-30-35&quot; href=&quot;manifest.xsf&quot; solutionVersion=&quot;1.0.0.1&quot; productVersion=&quot;15.0.0&quot; PIVersion=&quot;1.0.0.0&quot; ?&gt;
        ///&lt;?mso-application progid=&quot;InfoPath.Document&quot; versionProgid=&quot;InfoPath.Document.3&quot;?&gt;
        ///&lt;my:myFields xmlns:my=&quot;http://schemas.microsoft.com/office/infopath/2003/myXSD/2017-07-27T23:30:35&quot;&gt;
        ///	&lt;my:testInput&gt;&lt;/my:testInput&gt;
        ///&lt;/my:myFields&gt;
        ///.
        /// </summary>
        internal static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:my=&quot;http://schemas.microsoft.com/office/infopath/2003/myXSD/2017-07-27T23:30:35&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; xmlns:xd=&quot;http://schemas.microsoft.com/office/infopath/2003&quot; xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot; xmlns:xdExtension=&quot;http://schemas.microsoft.com/office/infopath/2003/xslt/extension&quot; xmlns:xdXDocument=&quot;http://schemas.microsoft.com/office/infopath/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string view1 {
            get {
                return ResourceManager.GetString("view1", resourceCulture);
            }
        }
    }
}
